// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4DmwhpE9I1dyevkZO4Symju_M8Zm3ZGM',
    appId: '1:996836554263:web:74952251b5e3de1f158e52',
    messagingSenderId: '996836554263',
    projectId: 'chat-20597',
    authDomain: 'chat-20597.firebaseapp.com',
    storageBucket: 'chat-20597.appspot.com',
    measurementId: 'G-0WWVG3E07E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYmRWc6XdL2NbN-9VMkWUlzQnLmnkvc8M',
    appId: '1:996836554263:android:79d12a9a4243f16b158e52',
    messagingSenderId: '996836554263',
    projectId: 'chat-20597',
    storageBucket: 'chat-20597.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPYwQASKyy3FB2KkukzHOSGVDxVWz5684',
    appId: '1:996836554263:ios:067614de5b619598158e52',
    messagingSenderId: '996836554263',
    projectId: 'chat-20597',
    storageBucket: 'chat-20597.appspot.com',
    iosClientId: '996836554263-k8jgfq8kd6khintm7uu6mf34lirpsaob.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPYwQASKyy3FB2KkukzHOSGVDxVWz5684',
    appId: '1:996836554263:ios:88cf72b0cdc2bc0c158e52',
    messagingSenderId: '996836554263',
    projectId: 'chat-20597',
    storageBucket: 'chat-20597.appspot.com',
    iosClientId: '996836554263-hsf4go736d1injv9sl5mtj8k69qlq5uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
